openapi: "3.0.0"
info:
  title: Tshirt store API
  description: An Tshirt store api documentaiton for quick testing 
  version: 1.1.0
  contact:
    email: gouravmarch20@gmail.com
    url: "https://trixoon.com"